"use client";
import {useState} from "react";
import {BookOpen, Plus, Sparkles, Users, Globe2, FileText, ChevronRight, Search, MoreHorizontal} from "lucide-react";

const recent=[{title:"The Last Aurora",genre:"Fantasy • Adventure",chapters:12,progress:68,updated:"Baru saja"},{title:"Senja di Kota Hujan",genre:"Romance • Drama",chapters:8,progress:42,updated:"Kemarin"},{title:"Project Eclipse",genre:"Sci-Fi • Mystery",chapters:5,progress:25,updated:"3 hari lalu"}];
export default function Home(){
 const [showCreate,setShowCreate]=useState(false); const [query,setQuery]=useState("");
 const filtered=recent.filter(n=>n.title.toLowerCase().includes(query.toLowerCase()));
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><div className="brandIcon"><BookOpen size={19}/></div><span>Novelis</span></div><button className="newBtn" onClick={()=>setShowCreate(true)}><Plus size={18}/> Novel Baru</button><nav><a className="active"><BookOpen size={17}/> Proyek Novel</a><a><FileText size={17}/> Draft & Bab</a><a><Users size={17}/> Karakter</a><a><Globe2 size={17}/> Dunia Cerita</a></nav><div className="sideBottom"><div className="aiCard"><Sparkles size={16}/><div><b>AI Studio</b><small>Siap membantu cerita kamu.</small></div></div><div className="profile"><div className="avatar">F</div><div><b>Penulis</b><small>Workspace pribadi</small></div><MoreHorizontal size={17}/></div></div></aside>
  <section className="content"><header><div><p className="eyebrow">WORKSPACE PENULIS</p><h1>Selamat datang di Novelis.</h1><p className="sub">Bangun cerita, kembangkan karakter, dan biarkan AI membantu menulisnya.</p></div><button className="primary" onClick={()=>setShowCreate(true)}><Sparkles size={17}/> Mulai Novel</button></header>
   <div className="hero"><div><span className="pill"><Sparkles size={14}/> AI Novel Studio</span><h2>Dari satu ide menjadi<br/><em>sebuah cerita utuh.</em></h2><p>Mulai dari premis sederhana. Novelis membantu membuat outline, karakter, dunia, hingga bab demi bab.</p><button className="heroBtn" onClick={()=>setShowCreate(true)}>Buat Novel Pertama <ChevronRight size={17}/></button></div><div className="heroArt"><div className="orb orb1"></div><div className="orb orb2"></div><div className="book"><BookOpen size={46}/><span>YOUR<br/>STORY</span></div></div></div>
   <div className="sectionHead"><div><h3>Novel Saya</h3><p>Kelola semua cerita yang sedang kamu kerjakan.</p></div><div className="search"><Search size={16}/><input placeholder="Cari novel..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
   <div className="cards">{filtered.map(n=><article className="novelCard" key={n.title}><div className="cover"><span>{n.title.split(" ").slice(0,2).join(" ")}</span><small>NOVELIS</small></div><div className="cardBody"><div className="cardTop"><div><h4>{n.title}</h4><p>{n.genre}</p></div><button className="iconBtn"><MoreHorizontal size={18}/></button></div><div className="progressMeta"><span>{n.chapters} bab</span><span>{n.progress}%</span></div><div className="progress"><i style={{width:n.progress+"%"}}/></div><small className="updated">{n.updated}</small></div></article>)}<button className="emptyCard" onClick={()=>setShowCreate(true)}><div><Plus size={22}/></div><b>Buat novel baru</b><span>Mulai dari ide kamu</span></button></div>
  </section>
  {showCreate&&<div className="modalWrap" onMouseDown={e=>e.target===e.currentTarget&&setShowCreate(false)}><div className="modal"><div className="modalHead"><div><span className="pill"><Sparkles size={13}/> LANGKAH 1</span><h2>Buat Novel Baru</h2><p>Isi dasar cerita. Detailnya masih bisa diubah nanti.</p></div><button className="close" onClick={()=>setShowCreate(false)}>×</button></div><label>Judul novel<input autoFocus placeholder="Contoh: Senja yang Tak Pernah Pulang"/></label><label>Genre<select><option>Fantasy</option><option>Romance</option><option>Drama</option><option>Mystery</option><option>Science Fiction</option><option>Thriller</option></select></label><label>Ide cerita<textarea placeholder="Ceritakan ide singkat novelmu..."/></label><button className="primary full" onClick={()=>setShowCreate(false)}><Sparkles size={17}/> Lanjutkan ke Story Builder</button></div></div>}
 </main>
}